#pragma once

/**
 * Helpers to easier use of COM objects.
 * Generated by guid.py.
 */

#include <comip.h>
#include <comdef.h>

/**
 * Attach interfaces GUIDs to interfaces
 */
// IUnknown UUID
class DECLSPEC_UUID("00000000-0000-0000-C000-000000000046") IAIMPPlugin;

class DECLSPEC_UUID("504D4941-6341-6974-6F6E-000000000000") IAIMPAction;
class DECLSPEC_UUID("41494D50-4163-7469-6F6E-4576656E7400") IAIMPActionEvent;
class DECLSPEC_UUID("41494D50-4175-6469-6F44-656300000000") IAIMPAudioDecoder;
class DECLSPEC_UUID("41494D50-436F-6E66-6967-000000000000") IAIMPConfig;
class DECLSPEC_UUID("41494D50-436F-7265-0000-000000000000") IAIMPCore;
class DECLSPEC_UUID("41494D50-4572-7249-6E66-6F0000000000") IAIMPErrorInfo;
class DECLSPEC_UUID("41494D50-4578-7441-6C62-417274436174") IAIMPExtensionAlbumArtCatalog;
class DECLSPEC_UUID("41494D50-4578-7441-6C62-417274507276") IAIMPExtensionAlbumArtProvider;
class DECLSPEC_UUID("41494D50-4578-7441-7564-696F44656300") IAIMPExtensionAudioDecoder;
class DECLSPEC_UUID("41494D50-4578-7441-7564-696F4465634F") IAIMPExtensionAudioDecoderOld;
class DECLSPEC_UUID("41494D50-4578-7443-7374-6D5669730000") IAIMPExtensionCustomVisualization;
class DECLSPEC_UUID("41494D50-4578-7445-6D62-645669730000") IAIMPExtensionEmbeddedVisualization;
class DECLSPEC_UUID("41494D50-4578-7446-696C-654578706472") IAIMPExtensionFileExpander;
class DECLSPEC_UUID("41494D50-4578-7446-696C-65466D740000") IAIMPExtensionFileFormat;
class DECLSPEC_UUID("504D4941-7845-4674-696C-65496E666F00") IAIMPExtensionFileInfoProvider;
class DECLSPEC_UUID("41494D50-4578-7446-696C-65496E666F45") IAIMPExtensionFileInfoProviderEx;
class DECLSPEC_UUID("41494D50-4578-7450-6C61-796261636B51") IAIMPExtensionPlaybackQueue;
class DECLSPEC_UUID("41494D50-4578-7450-6C72-486F6F6B0000") IAIMPExtensionPlayerHook;
class DECLSPEC_UUID("41494D50-4578-7450-6C73-4D616E4C7472") IAIMPExtensionPlaylistManagerListener;
class DECLSPEC_UUID("41494D50-4578-7472-6E4F-7074446C6700") IAIMPExternalSettingsDialog;
class DECLSPEC_UUID("41494D50-4669-6C65-496E-666F00000000") IAIMPFileInfo;
class DECLSPEC_UUID("41494D50-4669-6C65-5374-7265616D0000") IAIMPFileStream;
class DECLSPEC_UUID("41494D50-4669-6C65-5461-670000000000") IAIMPFileTag;
class DECLSPEC_UUID("41494D50-4669-6C65-5461-674564697400") IAIMPFileTagEditor;
class DECLSPEC_UUID("41494D50-4874-7470-436C-744576747300") IAIMPHTTPClientEvents;
class DECLSPEC_UUID("41494D50-4861-7368-436F-646500000000") IAIMPHashCode;
class DECLSPEC_UUID("41494D50-496D-6167-6500-000000000000") IAIMPImage;
class DECLSPEC_UUID("41494D50-496D-6167-6543-6F6E746E7200") IAIMPImageContainer;
class DECLSPEC_UUID("41494D50-4D65-6D53-7472-65616D000000") IAIMPMemoryStream;
class DECLSPEC_UUID("41494D50-4D65-6E75-4974-656D00000000") IAIMPMenuItem;
class DECLSPEC_UUID("FC6FB524-A959-4089-AA0A-EA40AB7374CD") IAIMPMessageHook;
class DECLSPEC_UUID("41494D50-4F62-6A4C-6973-740000000000") IAIMPObjectList;
class DECLSPEC_UUID("41494D50-4F70-7444-6C67-4672616D6500") IAIMPOptionsDialogFrame;
class DECLSPEC_UUID("504D4941-6C50-7961-6261-636B5149746D") IAIMPPlaybackQueueItem;
class DECLSPEC_UUID("41494D50-506C-7300-0000-000000000000") IAIMPPlaylist;
class DECLSPEC_UUID("41494D50-506C-7347-726F-757000000000") IAIMPPlaylistGroup;
class DECLSPEC_UUID("41494D50-506C-7349-7465-6D0000000000") IAIMPPlaylistItem;
class DECLSPEC_UUID("41494D50-506C-734C-7374-6E7200000000") IAIMPPlaylistListener;
class DECLSPEC_UUID("41494D50-506C-7351-7565-756500000000") IAIMPPlaylistQueue;
class DECLSPEC_UUID("41494D50-5072-6F67-7265-737343420000") IAIMPProgressCallback;
class DECLSPEC_UUID("41494D50-5072-6F70-4C69-737400000000") IAIMPPropertyList;
class DECLSPEC_UUID("41494D50-5363-6865-6475-6C6572457674") IAIMPSchedulerEvent;
class DECLSPEC_UUID("41494D50-5372-7641-6374-696F6E4D616E") IAIMPServiceActionManager;
class DECLSPEC_UUID("41494D50-5372-7641-6C62-417274000000") IAIMPServiceAlbumArt;
class DECLSPEC_UUID("4941494D-5053-7276-416C-624172744368") IAIMPServiceAlbumArtCache;
class DECLSPEC_UUID("41494D50-5372-7641-7474-724578740000") IAIMPServiceAttrExtendable;
class DECLSPEC_UUID("41494D50-5372-7641-7474-724F626A7300") IAIMPServiceAttrObjects;
class DECLSPEC_UUID("41494D50-5372-7641-7564-696F44656300") IAIMPServiceAudioDecoders;
class DECLSPEC_UUID("41494D50-5372-7643-6667-000000000000") IAIMPServiceConfig;
class DECLSPEC_UUID("4941494D-5053-7276-436F-6E6E43666700") IAIMPServiceConnectionSettings;
class DECLSPEC_UUID("41494D50-5372-7646-696C-65466D747300") IAIMPServiceFileFormats;
class DECLSPEC_UUID("41494D50-5372-7646-696C-65496E666F00") IAIMPServiceFileInfo;
class DECLSPEC_UUID("41494D50-5372-7646-6C49-6E66466D7400") IAIMPServiceFileInfoFormatter;
class DECLSPEC_UUID("41494D50-5372-7646-6C49-6E66466D7455") IAIMPServiceFileInfoFormatterUtils;
class DECLSPEC_UUID("41494D50-5372-7646-696C-654D616E0000") IAIMPServiceFileManager;
class DECLSPEC_UUID("41494D50-5372-7646-696C-655374726D00") IAIMPServiceFileStreaming;
class DECLSPEC_UUID("41494D50-5372-7654-6167-456469740000") IAIMPServiceFileTagEditor;
class DECLSPEC_UUID("41494D50-5372-7648-7474-70436C740000") IAIMPServiceHTTPClient;
class DECLSPEC_UUID("41494D50-5372-764D-5549-000000000000") IAIMPServiceMUI;
class DECLSPEC_UUID("41494D50-5372-764D-656E-754D6E677200") IAIMPServiceMenuManager;
class DECLSPEC_UUID("41494D50-5372-764D-7367-447370720000") IAIMPServiceMessageDispatcher;
class DECLSPEC_UUID("41494D50-5372-764F-7074-446C67000000") IAIMPServiceOptionsDialog;
class DECLSPEC_UUID("504D4941-7253-5076-6C62-61636B510000") IAIMPServicePlaybackQueue;
class DECLSPEC_UUID("41494D50-5372-7650-6C61-796572000000") IAIMPServicePlayer;
class DECLSPEC_UUID("41494D50-5372-7650-6C73-4D616E000000") IAIMPServicePlaylistManager;
class DECLSPEC_UUID("41494D50-5372-7653-6368-6564756C6572") IAIMPServiceScheduler;
class DECLSPEC_UUID("41494D50-5372-7653-6875-74646F776E00") IAIMPServiceShutdown;
class DECLSPEC_UUID("504D4941-7253-5376-6B69-6E734D6E6772") IAIMPServiceSkinsManager;
class DECLSPEC_UUID("41494D50-5372-7653-796E-637200000000") IAIMPServiceSynchronizer;
class DECLSPEC_UUID("41494D50-5372-7654-6872-64506F6F6C00") IAIMPServiceThreadPool;
class DECLSPEC_UUID("41494D50-5372-7656-6572-496E666F0000") IAIMPServiceVersionInfo;
class DECLSPEC_UUID("41494D50-5372-7656-6973-75616C000000") IAIMPServiceVisualizations;
class DECLSPEC_UUID("41494D50-536B-696E-496E-666F00000000") IAIMPSkinInfo;
class DECLSPEC_UUID("41494D50-5374-7265-616D-000000000000") IAIMPStream;
class DECLSPEC_UUID("41494D50-5374-7269-6E67-000000000000") IAIMPString;
class DECLSPEC_UUID("41494D50-5461-736B-0000-000000000000") IAIMPTask;
class DECLSPEC_UUID("41494D50-5461-736B-4F77-6E6572000000") IAIMPTaskOwner;
class DECLSPEC_UUID("41494D50-5461-736B-5072-696F72697479") IAIMPTaskPriority;
class DECLSPEC_UUID("41494D50-5669-7274-7561-6C46696C6500") IAIMPVirtualFile;


/**
 * Defines for easy use of _com_ptr_t
 */
#define COM_PTR_T(x) _com_ptr_t<_com_IIID<x,  &__uuidof(x)>>
#define IAIMPActionPtr COM_PTR_T(IAIMPAction)
#define IAIMPActionEventPtr COM_PTR_T(IAIMPActionEvent)
#define IAIMPAudioDecoderPtr COM_PTR_T(IAIMPAudioDecoder)
#define IAIMPConfigPtr COM_PTR_T(IAIMPConfig)
#define IAIMPCorePtr COM_PTR_T(IAIMPCore)
#define IAIMPErrorInfoPtr COM_PTR_T(IAIMPErrorInfo)
#define IAIMPExtensionAlbumArtCatalogPtr COM_PTR_T(IAIMPExtensionAlbumArtCatalog)
#define IAIMPExtensionAlbumArtProviderPtr COM_PTR_T(IAIMPExtensionAlbumArtProvider)
#define IAIMPExtensionAudioDecoderPtr COM_PTR_T(IAIMPExtensionAudioDecoder)
#define IAIMPExtensionAudioDecoderOldPtr COM_PTR_T(IAIMPExtensionAudioDecoderOld)
#define IAIMPExtensionCustomVisualizationPtr COM_PTR_T(IAIMPExtensionCustomVisualization)
#define IAIMPExtensionEmbeddedVisualizationPtr COM_PTR_T(IAIMPExtensionEmbeddedVisualization)
#define IAIMPExtensionFileExpanderPtr COM_PTR_T(IAIMPExtensionFileExpander)
#define IAIMPExtensionFileFormatPtr COM_PTR_T(IAIMPExtensionFileFormat)
#define IAIMPExtensionFileInfoProviderPtr COM_PTR_T(IAIMPExtensionFileInfoProvider)
#define IAIMPExtensionFileInfoProviderExPtr COM_PTR_T(IAIMPExtensionFileInfoProviderEx)
#define IAIMPExtensionPlaybackQueuePtr COM_PTR_T(IAIMPExtensionPlaybackQueue)
#define IAIMPExtensionPlayerHookPtr COM_PTR_T(IAIMPExtensionPlayerHook)
#define IAIMPExtensionPlaylistManagerListenerPtr COM_PTR_T(IAIMPExtensionPlaylistManagerListener)
#define IAIMPExternalSettingsDialogPtr COM_PTR_T(IAIMPExternalSettingsDialog)
#define IAIMPFileInfoPtr COM_PTR_T(IAIMPFileInfo)
#define IAIMPFileStreamPtr COM_PTR_T(IAIMPFileStream)
#define IAIMPFileTagPtr COM_PTR_T(IAIMPFileTag)
#define IAIMPFileTagEditorPtr COM_PTR_T(IAIMPFileTagEditor)
#define IAIMPHTTPClientEventsPtr COM_PTR_T(IAIMPHTTPClientEvents)
#define IAIMPHashCodePtr COM_PTR_T(IAIMPHashCode)
#define IAIMPImagePtr COM_PTR_T(IAIMPImage)
#define IAIMPImageContainerPtr COM_PTR_T(IAIMPImageContainer)
#define IAIMPMemoryStreamPtr COM_PTR_T(IAIMPMemoryStream)
#define IAIMPMenuItemPtr COM_PTR_T(IAIMPMenuItem)
#define IAIMPMessageHookPtr COM_PTR_T(IAIMPMessageHook)
#define IAIMPObjectListPtr COM_PTR_T(IAIMPObjectList)
#define IAIMPOptionsDialogFramePtr COM_PTR_T(IAIMPOptionsDialogFrame)
#define IAIMPPlaybackQueueItemPtr COM_PTR_T(IAIMPPlaybackQueueItem)
#define IAIMPPlaylistPtr COM_PTR_T(IAIMPPlaylist)
#define IAIMPPlaylistGroupPtr COM_PTR_T(IAIMPPlaylistGroup)
#define IAIMPPlaylistItemPtr COM_PTR_T(IAIMPPlaylistItem)
#define IAIMPPlaylistListenerPtr COM_PTR_T(IAIMPPlaylistListener)
#define IAIMPPlaylistQueuePtr COM_PTR_T(IAIMPPlaylistQueue)
#define IAIMPProgressCallbackPtr COM_PTR_T(IAIMPProgressCallback)
#define IAIMPPropertyListPtr COM_PTR_T(IAIMPPropertyList)
#define IAIMPSchedulerEventPtr COM_PTR_T(IAIMPSchedulerEvent)
#define IAIMPServiceActionManagerPtr COM_PTR_T(IAIMPServiceActionManager)
#define IAIMPServiceAlbumArtPtr COM_PTR_T(IAIMPServiceAlbumArt)
#define IAIMPServiceAlbumArtCachePtr COM_PTR_T(IAIMPServiceAlbumArtCache)
#define IAIMPServiceAttrExtendablePtr COM_PTR_T(IAIMPServiceAttrExtendable)
#define IAIMPServiceAttrObjectsPtr COM_PTR_T(IAIMPServiceAttrObjects)
#define IAIMPServiceAudioDecodersPtr COM_PTR_T(IAIMPServiceAudioDecoders)
#define IAIMPServiceConfigPtr COM_PTR_T(IAIMPServiceConfig)
#define IAIMPServiceConnectionSettingsPtr COM_PTR_T(IAIMPServiceConnectionSettings)
#define IAIMPServiceFileFormatsPtr COM_PTR_T(IAIMPServiceFileFormats)
#define IAIMPServiceFileInfoPtr COM_PTR_T(IAIMPServiceFileInfo)
#define IAIMPServiceFileInfoFormatterPtr COM_PTR_T(IAIMPServiceFileInfoFormatter)
#define IAIMPServiceFileInfoFormatterUtilsPtr COM_PTR_T(IAIMPServiceFileInfoFormatterUtils)
#define IAIMPServiceFileManagerPtr COM_PTR_T(IAIMPServiceFileManager)
#define IAIMPServiceFileStreamingPtr COM_PTR_T(IAIMPServiceFileStreaming)
#define IAIMPServiceFileTagEditorPtr COM_PTR_T(IAIMPServiceFileTagEditor)
#define IAIMPServiceHTTPClientPtr COM_PTR_T(IAIMPServiceHTTPClient)
#define IAIMPServiceMUIPtr COM_PTR_T(IAIMPServiceMUI)
#define IAIMPServiceMenuManagerPtr COM_PTR_T(IAIMPServiceMenuManager)
#define IAIMPServiceMessageDispatcherPtr COM_PTR_T(IAIMPServiceMessageDispatcher)
#define IAIMPServiceOptionsDialogPtr COM_PTR_T(IAIMPServiceOptionsDialog)
#define IAIMPServicePlaybackQueuePtr COM_PTR_T(IAIMPServicePlaybackQueue)
#define IAIMPServicePlayerPtr COM_PTR_T(IAIMPServicePlayer)
#define IAIMPServicePlaylistManagerPtr COM_PTR_T(IAIMPServicePlaylistManager)
#define IAIMPServiceSchedulerPtr COM_PTR_T(IAIMPServiceScheduler)
#define IAIMPServiceShutdownPtr COM_PTR_T(IAIMPServiceShutdown)
#define IAIMPServiceSkinsManagerPtr COM_PTR_T(IAIMPServiceSkinsManager)
#define IAIMPServiceSynchronizerPtr COM_PTR_T(IAIMPServiceSynchronizer)
#define IAIMPServiceThreadPoolPtr COM_PTR_T(IAIMPServiceThreadPool)
#define IAIMPServiceVersionInfoPtr COM_PTR_T(IAIMPServiceVersionInfo)
#define IAIMPServiceVisualizationsPtr COM_PTR_T(IAIMPServiceVisualizations)
#define IAIMPSkinInfoPtr COM_PTR_T(IAIMPSkinInfo)
#define IAIMPStreamPtr COM_PTR_T(IAIMPStream)
#define IAIMPStringPtr COM_PTR_T(IAIMPString)
#define IAIMPTaskPtr COM_PTR_T(IAIMPTask)
#define IAIMPTaskOwnerPtr COM_PTR_T(IAIMPTaskOwner)
#define IAIMPTaskPriorityPtr COM_PTR_T(IAIMPTaskPriority)
#define IAIMPVirtualFilePtr COM_PTR_T(IAIMPVirtualFile)
